### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by adam-sse** [adam-sse/ai-perf-worker#1]
- [x] auf dgx-1 zum laufen kriegen (oder irgendwie anders auf GPU) **(Leo)**
    - [x] Alternativ: Backup Lösung finden
- [x] neue Parameter umsetzen im worker (möglichst "generisch" lösen, das man nicht immer alle parameter im controller setzen muss) **(Adam)**
- [x] numpy random seed: effekt messen **(Adam)**
- [x] generisch andere machine learning Anwendungsfälle ermöglichen (vererbung?) **(Leo)**
